config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: "about"
  get "users/:id" => "users#show", as: :mypage
  resources :users , only: [:show, :index, :edit, :new, :destroy, :update]
  resources :books
  patch 'books/:id' => 'books#update', as: 'update_book'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app', 'assets', 'images', 'no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def set_current_user
    @current_user=User.find_by(id :session[:user_id])
  end


  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]) #ページネーション機能
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice]="successfully updated !"
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end

  def index
    @users = User.page(params[:page]) #ページネーション機能
    @user = current_user
    @book = Book.new
  end

private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to  new_user_session_path #ログイン画面へと直ったかな？
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>User info</h2>
  <div class="user_edit">
    <% if @user.errors.any? %>
      <div class="alert alert-warning">
      <%= @user.errors.count %> errors prohibited this book from being saved:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @user, method: :patch do |f| %>
      <div>
      <label for="inputName">Name</label><br>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
      </div>
      <div>
      <label for = "inputImage">Image</label><br>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像",accept:"image/*" %>
      </div>
      <label for ="inputIntro">introduction</label><br>
      <%= f.text_area :introduction, placeholder:"紹介" %><br>
      <%= f.submit "Update User" %>
    <% end %>
  </div>

app/views/users/index.html.erb
<body>
<div class= "container px-5 px-sm-0">
  <div class = "row">
  <!--ｻｲﾄﾞﾊﾞｰ-->
    <div class = "col-md-3">
      <%= render partial: 'shared/sidebar', locals: { user: @user, book: @book, books: @books } %>
    </div>

  <!--メインコンテンツ-->
  <div class="col-md-8 offset-md-1">
    <div class="user_index">
      <h2>Users</h2>
        <table class="table table-hover table-inverse" width="100%;" >
          <thead>
            <tr>
              <th width="10%">Image</th>
              <th width="10%">Name</th>
              <th width="70%">Introdution</th>
              <th width="10%"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= user.introduction %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
            <% end %>
              <%= paginate @users %>
          </tbody>
        </table>
      </div>
  </div>

  </div>
</div>
</body>

app/views/users/show.html.erb
<body>
<div class= "container px-5 px-sm-0">
  <%#= render partial: 'shared/errors_msg', locals: {book: @book} %>
  <div class = "row">
  <!--ｻｲﾄﾞﾊﾞｰ-->
    <div class = "col-md-3">
      <%= render partial: 'shared/sidebar', locals: { user: @user, book: @book, books: @books } %>
    </div>

  <!--メインコンテンツ-->
  <div class="col-md-8 offset-md-1"> <!--左に統一-->
    <div class="user_books">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th width="10%"></th>
              <th width="20%">Title</th>
              <th width="70%">Opinion</th>
              <% if @user.id == current_user.id %>
                <th></th>
                <th></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <% if @user.id == current_user.id %>
              <td><%= link_to 'Edit', edit_book_path(book.id), class: "btn btn-success"%></td>
              <td><%= link_to 'Destroy', book_path(book.id), {method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger"} %></td>
              <% end %>
            </tr>
            <% end %>
              <%= paginate @books %>
        </tbody>
      </table>
    </div>
  </div>

  </div>
</div>
</body>