config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: "about"
  get "users/:id" => "users#show", as: :mypage
  resources :users , only: [:show, :index, :edit, :new, :destroy, :update]
  resources :books
  patch 'books/:id' => 'books#update', as: 'update_book'

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, {presence: true, length: {maximum: 200}}
end

app/controllers/books/confirmations_controller.rb
# frozen_string_literal: true

class Books::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/books/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Books::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/books/passwords_controller.rb
# frozen_string_literal: true

class Books::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/books/registrations_controller.rb
# frozen_string_literal: true

class Books::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/books/sessions_controller.rb
# frozen_string_literal: true

class Books::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/books/unlocks_controller.rb
# frozen_string_literal: true

class Books::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]


  #投稿データの作成
  def new
    @book = Book.new
  end

  #投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="Book was successfully created !"
      redirect_to @book
    else
      @books = Book.order("id DESC").page(params[:page])
      @user = current_user
      render :new
    end
  end

  def index
    @books = Book.order("id DESC").page(params[:page]) #ページネーション機能
    @user = current_user
    @book = Book.new

  end

  def show
    @books = Book.find(params[:id])
    @user = @books.user
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated !"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] ="Book was successfully destroyed !"
    redirect_to '/books'
  end


  private
    def book_params # 投稿データのストロングパラメータ
      params.require(:book).permit(:title, :body)
    end

    def is_matching_login_user
      @book = Book.find(params[:id])
      unless @book.user_id == current_user.id
        redirect_to  "/books"
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
  <div class="book_edit">
		<% if @book.errors.any? %>
		  <div class="alert alert-warning">
  		<%= @book.errors.count %> errors prohibited this book from being saved:
		    <ul>
		      <% @book.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>

    <%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>
      <div>
        <label for="inputTitle">Titel</label><br>
        <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"タイトル"  %>
      </div>
      <div>
        <label for="inputOpinion">Opinion</label><br>
        <%= f.text_area :body, placeholder:"感想" %><br>
        <%= f.submit 'Update Book'%>
      </div>
    <% end %>

    <%= link_to 'Show', @book %>|
    <%= link_to 'Back', books_path %>
  </div>

app/views/books/index.html.erb
<body>
<div class= "container px-5 px-sm-0">
  <div class = "row">
  <!--ｻｲﾄﾞﾊﾞｰ-->
    <div class = "col-md-3">
      <%= render partial: 'shared/sidebar', locals: { user: @user, book: @book, books: @books } %>
    </div>

  <!--メインコンテンツ-->
  <div class="col-md-8 offset-md-1">
    <div class="books_index">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th width="10%"></th>
            <th width="20%">Title</th>
            <th width="60%">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @books.each do |book| %>
              <td><%= image_tag book.user.get_profile_image(80,80) %><br>
                  <%= link_to book.user.name, user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <% if book.user.id == current_user.id %>
                <td><%= link_to 'Edit', edit_book_path(book.id), {class: "btn btn-success"} %></td>
                <td><%= link_to 'Destroy', book_path(book.id), {method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger"} %></td>
              <% else %>
                <td colspan="2"></td>
              <% end %>
              <td><%= book.created_at %></td>
          </tr>
            <% end %>
              <%= paginate @books %>
        </tbody>
      </table>
    </div>
  </div>

  </div>
</div>
</body>

app/views/books/new.html.erb
<body>
<div class= "container px-5 px-sm-0">
  <!--バリデーションエラーの表示（これがやりたかった）-->
  <% if @book.errors.any? %>
  <div class="alert alert-warning">
  <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class = "row">
  <!--ｻｲﾄﾞﾊﾞｰ-->
  <div class = "col-md-3">
    <div class="user_info">
      <h2>User Info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>  <!--ﾕｰｻﾞｰの画像-->
        <table class="table">
          <tbody><tr></tr>
          <tr>
        	  <th>name</th>
        	  <th><%= @user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= @user.introduction %></th>
          </tr>
          </tbody>
        </table>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
    </div>
<br>

    <div class="new_book">
      <h2>New book</h2>
        <%= form_with model: @book do |f| %>

          <div>
            <label for="inputTitle">Titel</label><br>
              <%= f.text_field :title, autofocus: true, id:"inputTitle" %>
          </div>
          <div>
            <label for="inputOpinion">Opinion</label><br>
              <%= f.text_area :body %><br>
              <%= f.submit 'Create Books', class: "btn btn-success"%>
          </div>
        <% end %>
    </div>
  </div>

  <!--メインコンテンツ-->
  <div class="col-md-8 offset-md-1">
    <div class="books_index">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th width="10%"></th>
            <th width="20%">Title</th>
            <th width="60%">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @books.each do |book| %>
              <td><%= image_tag book.user.get_profile_image(80,80) %><br>
                  <%= link_to book.user.name, user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <% if book.user.id == current_user.id %>
                <td><%= link_to 'Edit', edit_book_path(book.id), {class: "btn btn-success"} %></td>
                <td><%= link_to 'Destroy', book_path(book.id), {method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger"} %></td>
              <% else %>
                <td colspan="2"></td>
              <% end %>
              <td><%= book.created_at %></td>
          </tr>
            <% end %>
              <%= paginate @books %>
        </tbody>
      </table>
    </div>
  </div>

  </div>
</div>
</body>

app/views/books/show.html.erb
<body>
<div class= "container px-5 px-sm-0">
  <div class = "row">
    <!--ｻｲﾄﾞﾊﾞｰ-->
    <div class = "col-md-3">
    <%= render partial: 'shared/sidebar', locals: { user: @user, book: @book, books: @books } %>
    </div>

    <!--メインコンテンツ-->
    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
          <th width="10%"></th>
          <th width="20%">Title</th>
          <th width="60%">Opinion</th>
          <th colspan="3"></th>
          </tr>
        </thead>
        <tbody> <!--いったん@booksを解除する20:08-->
          <tr>
          <td><%= image_tag @user.get_profile_image(80,80) %><br>
              <%= link_to @user.name, user_path(@user.id) %></td>
          <td><%= link_to @books.title, book_path(@books.id) %></td>
          <td><%= @books.body%></td>
            <% if @user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@books.id), class: "btn btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@books.id), {method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-danger"} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

</body>