config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#top'
  get 'home/about' => 'homes#about', as: "about"
  get "users/:id" => "users#show", as: :mypage
  resources :users , only: [:show, :index, :edit, :new, :destroy, :update]
  resources :books
  patch 'books/:id' => 'books#update', as: 'update_book'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!--ここからBootsstrap-->
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

  <!-- Rspecでは、aタグを検索していたので、button_toではなく、link_toを採用。-->
              <% if user_signed_in? %>

                <%= link_to user_path(current_user.id) , class: "btn nav-link" do %>
                <i class="fas fa-home" style="color: #ffffff;"></i> Home
                <% end %>

                <%= link_to users_path, class: "btn nav-link" do %>
                <i class="fas fa-users" style="color: #ffffff;"></i> Users
                <% end %>

                <%= link_to books_path, class: "btn nav-link" do %>
                <i class="fas fa-book-open" style="color: #ffffff;"></i> Books
                <% end %>

                <%= link_to destroy_user_session_path, {method: :delete, class: "btn nav-link"} do %>
                <i class="fas fa-sign-out-alt" style="color: #ffffff;"></i> Log out
                <% end %>

              <% else %>

                <%= link_to root_path, class: "btn nav-link" do %>
                <i class="fas fa-home" style="color: #ffffff;"></i>Home
                <% end %>

                <%= link_to '/home/about', class: "btn nav-link" do %>
                <i class="fas fa-link" style="color: #ffffff;"></i> About
                <% end %>

                <%= link_to new_user_registration_path, class: "btn nav-link" do %>
                <i class="fas fa-user-plus" style="color: #ffffff;"></i> Sign up
                <% end %>

                <%= link_to new_user_session_path, class: "btn nav-link" do %>
                <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i> Log in
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
     <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>